#!/bin/bash

# $1 -> file name

file_name="$1"

temp_file_path="$(mktemp -u --suffix '.mp4')"

ffmpeg\
    -i "$file_name"\
    -c copy\
    "$temp_file_path"

ffmpeg\
    -i "$temp_file_path"\
    -pix_fmt yuv420p\
    -crf 28\
    "${file_name%.*}_yuv420p.mp4"

rm "$temp_file_path"

